//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodManagementEntities3 : DbContext
    {
        public FoodManagementEntities3()
            : base("name=FoodManagementEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FoodItem> FoodItems { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment1> Payment1 { get; set; }
        public virtual DbSet<Restaurent> Restaurents { get; set; }
    }
}
