//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> CId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public Nullable<int> FoodId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual FoodItem FoodItem { get; set; }
    }
}
