//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment1
    {
        public int Id { get; set; }
        public Nullable<int> CId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> OrderID { get; set; }
    }
}
